name: flutter_screen_recording
description: A new Flutter plugin for record the screen. This plugin can be used for record the screen on android, iOS, and web devices.
version: 2.0.7
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_foreground_task: ^3.7.3
  flutter_screen_recording_platform_interface:
    git:
      url : https://github.com/clintontopclass/screen_recording_platform_interface
      ref : "a1756ae"
  flutter_screen_recording_web:
    git:
      url : https://github.com/clintontopclass/screen_recording_web
      ref : "acdbe8b"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.isvisoft.flutter_screen_recording
        pluginClass: FlutterScreenRecordingPlugin
      ios:
        pluginClass: FlutterScreenRecordingPlugin
      web:
        default_package: flutter_screen_recording_web
